[tool.black]
line-length     = 120
target-version  = ["py310"]
include         = ".*py$"

[tool.flake8]
count = true
max-complexity = 20
max-function-length = 130
# Technically this is 120, but black has a policy of "1 or 2 over is fine if it is tidier", so we have to raise this.
max-line-length = 130
show_source = false
statistics = false
accept-encodings = "utf-8"
docstring-convention = "numpy"
ignore = [
    "A002",    # Argument is shadowing a python builtin.
    "A003",    # Class attribute is shadowing a python builtin.
    "CFQ002",  # Function has too many arguments.
    "CFQ004",  # Function has too many returns.
    "E402",    # Module level import not at top of file (isn't compatible with our import style).
    "IFS001",  # "use a oneliner here".
    "T101",    # TO-DO comment detection (T102 is FIX-ME and T103 is XXX).
    "W503",    # line break before binary operator.
    "W504",    # line break before binary operator (again, I guess).
    "S101",    # Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
    "E203",    # whitespace before ':'
    "E231",    # missing whitespace after ','
]
# F403: cannot detect unused vars if we use starred import
# F405: __all__ field may be undefined or defined from star imports
per-file-ignores = [
    "reinhard/utility/__init__.py: F403,F405"
]

[tool.isort]
profile = "black"
multi_line_output = 9

[tool.pyright]
include = ["reinhard"]

reportMissingImports = true
reportMissingTypeStubs = true

pythonVersion = "3.10"
typeCheckingMode = "strict"
reportIncompatibleMethodOverride = "warning"  # This relies on ordering for key-word only arguments which is annoying
                                           # than it's worth
reportUnknownMemberType = "warning"  # This messes with instance checking generic objects
reportUnknownArgumentType = "warning"  # Pretty much the same as reportUnknownMemberType
reportUnknownParameterType = "warning"  # Pretty much the same as reportUnknownMemberType
reportUnusedFunction = "warning"  # This assumes decorator calls don't load a function into something for usage
reportImportCycles = "warning"                  # This isn't necessarily an issue if it's type checking only.
