[tool.black]
line-length     = 120
target-version  = ["py39"]
include         = ".*py$"

[tool.isort]
profile = "black"
force_single_line = true

[tool.pyright]
include = ["reinhard"]

reportMissingImports = true
reportMissingTypeStubs = true

pythonVersion = "3.10"
typeCheckingMode = "strict"
reportIncompatibleMethodOverride = "warning"  # This relies on ordering for key-word only arguments which is annoying
                                           # than it's worth
reportUnknownMemberType = "warning"  # This messes with instance checking generic objects
reportUnknownArgumentType = "warning"  # Pretty much the same as reportUnknownMemberType
reportUnknownParameterType = "warning"  # Pretty much the same as reportUnknownMemberType
reportUnusedFunction = "warning"  # This assumes decorator calls don't load a function into something for usage
